# Getting Started with HPXPy

HPXPy provides a NumPy-like interface for parallel and distributed array computing, powered by the HPX C++ runtime system.

This tutorial covers:
- Initializing the HPX runtime
- Creating arrays
- Basic operations
- Array properties and methods

## 1. Setup and Runtime Initialization

First, let's import HPXPy and initialize the runtime.

In [1]:
import hpxpy as hpx
import numpy as np

print(f"HPXPy version: {hpx.__version__}")

HPXPy version: 0.1.0


In [2]:
# Initialize the HPX runtime
# You can optionally specify the number of threads
hpx.init()

print(f"HPX is running: {hpx.is_running()}")
print(f"Number of threads: {hpx.num_threads()}")
print(f"Number of localities: {hpx.num_localities()}")
print(f"Current locality ID: {hpx.locality_id()}")

HPX is running: True
Number of threads: 12
Number of localities: 1
Current locality ID: 0


## 2. Creating Arrays

HPXPy provides NumPy-like array creation functions.

In [3]:
# Create arrays filled with zeros or ones
zeros = hpx.zeros(10)
ones = hpx.ones((5, 4))  # Can use tuple for shape

print("Zeros array:", zeros.to_numpy())
print("\nOnes array shape:", ones.shape)
print("Ones array:\n", ones.to_numpy())

Zeros array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Ones array shape: (5, 4)
Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# Create arrays with ranges
a = hpx.arange(10)           # 0 to 9
b = hpx.arange(5, 15)        # 5 to 14
c = hpx.arange(0, 20, 2)     # Even numbers 0-18
d = hpx.linspace(0, 1, 5)    # 5 evenly spaced values from 0 to 1

print("arange(10):", a.to_numpy())
print("arange(5, 15):", b.to_numpy())
print("arange(0, 20, 2):", c.to_numpy())
print("linspace(0, 1, 5):", d.to_numpy())

arange(10): [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
arange(5, 15): [ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
arange(0, 20, 2): [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [5]:
# Create from NumPy arrays
np_array = np.array([1.5, 2.5, 3.5, 4.5, 5.5])
hpx_array = hpx.from_numpy(np_array)

print("Original NumPy:", np_array)
print("HPXPy array:", hpx_array.to_numpy())

# Or use hpx.array() for list/tuple input
from_list = hpx.array([10, 20, 30, 40, 50])
print("From list:", from_list.to_numpy())

Original NumPy: [1.5 2.5 3.5 4.5 5.5]
HPXPy array: [1.5 2.5 3.5 4.5 5.5]
From list: [10 20 30 40 50]


## 3. Array Properties

HPXPy arrays have familiar NumPy-like properties.

In [6]:
arr = hpx.arange(24).reshape((2, 3, 4))

print(f"Shape: {arr.shape}")
print(f"Size (total elements): {arr.size}")
print(f"Number of dimensions: {arr.ndim}")
print(f"Data type: {arr.dtype}")

Shape: (2, 3, 4)
Size (total elements): 24
Number of dimensions: 3
Data type: float64


In [7]:
# Indexing and slicing
arr = hpx.arange(10)
print("Original:", arr.to_numpy())
print(f"First element: {arr[0]}")
print(f"Last element: {arr[-1]}")
print(f"Slice [2:7]: {arr[2:7].to_numpy()}")
print(f"Every other [::2]: {arr[::2].to_numpy()}")

Original: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
First element: 0.0
Last element: 9.0
Slice [2:7]: [2. 3. 4. 5. 6.]
Every other [::2]: [0. 2. 4. 6. 8.]


## 4. Basic Operations

HPXPy supports standard arithmetic operations.

In [8]:
a = hpx.arange(5)
b = hpx.ones(5) * 2

print("a:", a.to_numpy())
print("b:", b.to_numpy())
print()
print("a + b:", (a + b).to_numpy())
print("a - b:", (a - b).to_numpy())
print("a * b:", (a * b).to_numpy())
print("a / b:", (a / b).to_numpy())
print("a ** 2:", (a ** 2).to_numpy())

a: [0. 1. 2. 3. 4.]
b: [2. 2. 2. 2. 2.]

a + b: [2. 3. 4. 5. 6.]
a - b: [-2. -1.  0.  1.  2.]
a * b: [0. 2. 4. 6. 8.]
a / b: [0.  0.5 1.  1.5 2. ]
a ** 2: [ 0.  1.  4.  9. 16.]


In [9]:
# Operations with scalars
arr = hpx.arange(5)

print("Original:", arr.to_numpy())
print("arr + 10:", (arr + 10).to_numpy())
print("arr * 3:", (arr * 3).to_numpy())
print("10 - arr:", (10 - arr).to_numpy())

Original: [0. 1. 2. 3. 4.]
arr + 10: [10. 11. 12. 13. 14.]
arr * 3: [ 0.  3.  6.  9. 12.]
10 - arr: [10.  9.  8.  7.  6.]


In [10]:
# Comparison operations
arr = hpx.arange(10)

print("Array:", arr.to_numpy())
print("arr > 5:", (arr > 5).to_numpy())
print("arr == 3:", (arr == 3).to_numpy())
print("arr <= 3:", (arr <= 3).to_numpy())

Array: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


arr > 5: [False False False False False False  True  True  True  True]
arr == 3: [False False False  True False False False False False False]
arr <= 3: [ True  True  True  True False False False False False False]


## 5. Reductions

Reduction operations compute a single value from an array.

In [11]:
arr = hpx.arange(1, 11)  # 1 to 10

print("Array:", arr.to_numpy())
print(f"Sum: {hpx.sum(arr)}")
print(f"Product: {hpx.prod(arr)}")
print(f"Min: {hpx.min(arr)}")
print(f"Max: {hpx.max(arr)}")
print(f"Mean: {hpx.mean(arr)}")
print(f"Std: {hpx.std(arr):.4f}")

Array: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Sum: 55.0
Product: 3628800.0
Min: 1.0
Max: 10.0
Mean: 5.5
Std: 2.8723


## 6. Using the Context Manager

For cleaner code, you can use the `hpx.runtime()` context manager.

In [12]:
# First, let's finalize the current runtime
hpx.finalize()
print("Runtime finalized")

Runtime finalized


In [13]:
# Using context manager (automatically handles init/finalize)
with hpx.runtime(num_threads=4) as rt:
    arr = hpx.arange(1000000)
    total = hpx.sum(arr)
    print(f"Sum of 0 to 999999: {total}")
    print(f"(Expected: {999999 * 1000000 // 2})")

print("Runtime automatically finalized after context")

Sum of 0 to 999999: 499999500000.0
(Expected: 499999500000)
Runtime automatically finalized after context


## Summary

In this tutorial, you learned:

1. **Runtime Management**: Use `hpx.init()` / `hpx.finalize()` or the `hpx.runtime()` context manager
2. **Array Creation**: `zeros`, `ones`, `arange`, `linspace`, `from_numpy`, `array`
3. **Array Properties**: `shape`, `size`, `ndim`, `dtype`
4. **Operations**: Arithmetic (`+`, `-`, `*`, `/`, `**`), comparisons (`>`, `<`, `==`)
5. **Reductions**: `sum`, `prod`, `min`, `max`, `mean`, `std`

Next tutorial: **Parallel Algorithms** - Learn about sorting, scanning, and math functions.