# Parallel Algorithms in HPXPy

HPXPy provides parallel implementations of common algorithms that automatically utilize multiple CPU cores.

This tutorial covers:
- Math functions (element-wise operations)
- Sorting algorithms
- Scan operations (cumulative sum/product)
- Random number generation
- Execution policies

In [1]:
import hpxpy as hpx
import numpy as np

# Initialize HPX runtime
hpx.init()
print(f"Running with {hpx.num_threads()} threads")

Running with 12 threads


## 1. Element-wise Math Functions

HPXPy provides parallel implementations of common mathematical functions.

In [2]:
# Basic math operations
arr = hpx.array([1.0, 4.0, 9.0, 16.0, 25.0])

print("Original:", arr.to_numpy())
print("sqrt:", hpx.sqrt(arr).to_numpy())
print("square:", hpx.square(arr).to_numpy())
print("abs:", hpx.abs(hpx.array([-1, -2, 3, -4, 5])).to_numpy())
print("sign:", hpx.sign(hpx.array([-5, -1, 0, 1, 5])).to_numpy())

Original: [ 1.  4.  9. 16. 25.]
sqrt: [1. 2. 3. 4. 5.]
square: [  1.  16.  81. 256. 625.]
abs: [1 2 3 4 5]
sign: [-1 -1  0  1  1]


In [3]:
# Exponential and logarithmic functions
arr = hpx.array([0.0, 1.0, 2.0, 3.0])

print("Original:", arr.to_numpy())
print("exp:", hpx.exp(arr).to_numpy())
print("exp2 (2^x):", hpx.exp2(arr).to_numpy())

positive = hpx.array([1.0, 10.0, 100.0, 1000.0])
print("\nPositive:", positive.to_numpy())
print("log (natural):", hpx.log(positive).to_numpy())
print("log2:", hpx.log2(positive).to_numpy())
print("log10:", hpx.log10(positive).to_numpy())

Original: [0. 1. 2. 3.]
exp: [ 1.          2.71828183  7.3890561  20.08553692]
exp2 (2^x): [1. 2. 4. 8.]

Positive: [   1.   10.  100. 1000.]
log (natural): [0.         2.30258509 4.60517019 6.90775528]
log2: [0.         3.32192809 6.64385619 9.96578428]
log10: [0. 1. 2. 3.]


In [4]:
# Trigonometric functions
angles = hpx.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

print("Angles (radians):", angles.to_numpy())
print("sin:", np.round(hpx.sin(angles).to_numpy(), 4))
print("cos:", np.round(hpx.cos(angles).to_numpy(), 4))
print("tan:", np.round(hpx.tan(angles).to_numpy(), 4))

Angles (radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sin: [0.     0.5    0.7071 0.866  1.    ]
cos: [1.     0.866  0.7071 0.5    0.    ]
tan: [0.00000000e+00 5.77400000e-01 1.00000000e+00 1.73210000e+00
 1.63312394e+16]


In [5]:
# Hyperbolic functions
x = hpx.array([-2.0, -1.0, 0.0, 1.0, 2.0])

print("x:", x.to_numpy())
print("sinh:", np.round(hpx.sinh(x).to_numpy(), 4))
print("cosh:", np.round(hpx.cosh(x).to_numpy(), 4))
print("tanh:", np.round(hpx.tanh(x).to_numpy(), 4))

x: [-2. -1.  0.  1.  2.]
sinh: [-3.6269 -1.1752  0.      1.1752  3.6269]
cosh: [3.7622 1.5431 1.     1.5431 3.7622]
tanh: [-0.964  -0.7616  0.      0.7616  0.964 ]


In [6]:
# Rounding functions
arr = hpx.array([-2.7, -1.5, -0.3, 0.3, 1.5, 2.7])

print("Original:", arr.to_numpy())
print("floor:", hpx.floor(arr).to_numpy())
print("ceil:", hpx.ceil(arr).to_numpy())
print("trunc:", hpx.trunc(arr).to_numpy())

Original: [-2.7 -1.5 -0.3  0.3  1.5  2.7]
floor: [-3. -2. -1.  0.  1.  2.]
ceil: [-2. -1. -0.  1.  2.  3.]
trunc: [-2. -1. -0.  0.  1.  2.]


## 2. Element-wise Array Operations

Operations that work element-by-element on arrays.

In [7]:
# Element-wise minimum and maximum
a = hpx.array([1, 5, 3, 7, 2])
b = hpx.array([4, 2, 6, 1, 8])

print("a:", a.to_numpy())
print("b:", b.to_numpy())
print("maximum(a, b):", hpx.maximum(a, b).to_numpy())
print("minimum(a, b):", hpx.minimum(a, b).to_numpy())

a: [1 5 3 7 2]
b: [4 2 6 1 8]
maximum(a, b): [4 5 6 7 8]
minimum(a, b): [1 2 3 1 2]


In [8]:
# Clip and power
arr = hpx.arange(10)

print("Original:", arr.to_numpy())
print("clip(arr, 2, 7):", hpx.clip(arr, 2, 7).to_numpy())
print("power(arr, 2):", hpx.power(arr, 2).to_numpy())
print("power(arr, 0.5):", np.round(hpx.power(arr, 0.5).to_numpy(), 3))

Original: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
clip(arr, 2, 7): [2. 2. 2. 3. 4. 5. 6. 7. 7. 7.]
power(arr, 2): [ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
power(arr, 0.5): [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]


In [9]:
# Conditional selection with where
arr = hpx.arange(10)
condition = arr > 5

print("Array:", arr.to_numpy())
print("Condition (arr > 5):", condition.to_numpy())

# where(condition, x, y): select from x where True, y where False
result = hpx.where(condition, arr * 10, arr)
print("where(arr > 5, arr*10, arr):", result.to_numpy())

Array: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Condition (arr > 5): [False False False False False False  True  True  True  True]
where(arr > 5, arr*10, arr): [ 0.  1.  2.  3.  4.  5. 60. 70. 80. 90.]


## 3. Sorting

HPXPy provides parallel sorting algorithms.

In [10]:
# Create an unsorted array
unsorted = hpx.array([64, 25, 12, 22, 11, 90, 45, 33])

print("Unsorted:", unsorted.to_numpy())

# Sort the array
sorted_arr = hpx.sort(unsorted)
print("Sorted:", sorted_arr.to_numpy())

# Get sorting indices
indices = hpx.argsort(unsorted)
print("Sort indices:", indices.to_numpy())

Unsorted: [64 25 12 22 11 90 45 33]
Sorted: [11 12 22 25 33 45 64 90]
Sort indices: [4 2 3 1 7 6 0 5]


In [11]:
# Sorting larger arrays (parallel sort)
import time

# Create a large random array
large = hpx.random.uniform(0, 1000000, size=1000000)

start = time.time()
sorted_large = hpx.sort(large)
elapsed = time.time() - start

print(f"Sorted 1,000,000 elements in {elapsed:.3f} seconds")
print(f"First 10: {sorted_large[:10].to_numpy()}")
print(f"Last 10: {sorted_large[-10:].to_numpy()}")

Sorted 1,000,000 elements in 0.079 seconds
First 10: [3.8566516  3.94565805 4.31516582 5.09965219 6.39853562 6.65773665
 7.13786066 7.46091038 8.219913   9.13257234]
Last 10: [999988.989293   999992.44848805 999992.71447396 999992.77641553
 999993.27757915 999995.81836314 999996.18880818 999997.55263653
 999999.13337598 999999.33183037]


In [12]:
# Count occurrences
arr = hpx.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

print("Array:", arr.to_numpy())
for val in [1, 2, 3, 4, 5]:
    print(f"Count of {val}: {hpx.count(arr, val)}")

Array: [1 2 2 3 3 3 4 4 4 4]
Count of 1: 1
Count of 2: 2
Count of 3: 3
Count of 4: 4
Count of 5: 0


## 4. Scan Operations (Prefix Sums)

Scan operations compute cumulative results across an array.

In [13]:
arr = hpx.array([1, 2, 3, 4, 5])

print("Original:", arr.to_numpy())
print("cumsum:", hpx.cumsum(arr).to_numpy())
print("cumprod:", hpx.cumprod(arr).to_numpy())

Original: [1 2 3 4 5]
cumsum: [ 1  3  6 10 15]
cumprod: [  1   2   6  24 120]


In [14]:
# Practical example: Running total
daily_sales = hpx.array([100, 150, 200, 175, 250, 300, 225])

print("Daily sales:", daily_sales.to_numpy())
print("Running total:", hpx.cumsum(daily_sales).to_numpy())
print(f"Week total: {hpx.sum(daily_sales)}")

Daily sales: [100 150 200 175 250 300 225]
Running total: [ 100  250  450  625  875 1175 1400]
Week total: 1400


## 5. Random Number Generation

HPXPy provides parallel random number generation.

In [15]:
# Set seed for reproducibility
hpx.random.seed(42)

# Uniform random in [0, 1)
uniform = hpx.random.rand(10)
print("Uniform [0,1):", np.round(uniform.to_numpy(), 3))

# Uniform with custom range
custom_uniform = hpx.random.uniform(10, 20, size=10)
print("Uniform [10,20):", np.round(custom_uniform.to_numpy(), 2))

Uniform [0,1): [0.755 0.639 0.752 0.136 0.903 0.094 0.575 0.373 0.274 0.39 ]
Uniform [10,20): [10.12 15.24 16.85 16.37 18.27 19.46 17.53 14.49 10.47 10.65]


In [16]:
# Standard normal distribution
normal = hpx.random.randn(10)
print("Standard normal:", np.round(normal.to_numpy(), 3))

# Generate larger sample and check statistics
large_normal = hpx.random.randn(100000)
print(f"\nLarge sample (100k):")
print(f"  Mean: {hpx.mean(large_normal):.4f} (expected: 0)")
print(f"  Std:  {hpx.std(large_normal):.4f} (expected: 1)")

Standard normal: [ 0.45  -0.638 -0.167 -0.893  1.415 -2.524  0.312 -0.431  1.153 -0.829]

Large sample (100k):
  Mean: 0.0038 (expected: 0)


  Std:  1.0012 (expected: 1)


In [17]:
# Random integers
dice_rolls = hpx.random.randint(1, 7, size=20)  # Simulating dice
print("Dice rolls:", dice_rolls.to_numpy())

# Count each outcome
print("\nDistribution:")
for val in range(1, 7):
    count = hpx.count(dice_rolls, val)
    print(f"  {val}: {'*' * count} ({count})")

Dice rolls: [6 6 3 6 3 1 3 4 6 6 4 4 4 6 5 1 6 5 2 4]

Distribution:
  1: ** (2)
  2: * (1)
  3: *** (3)
  4: ***** (5)
  5: ** (2)
  6: ******* (7)


In [18]:
# Multi-dimensional random arrays
matrix = hpx.random.rand(3, 4)
print("Random 3x4 matrix:")
print(np.round(matrix.to_numpy(), 3))

Random 3x4 matrix:
[[0.957 0.003 0.621 0.164]
 [0.223 0.181 0.044 0.301]
 [0.948 0.85  0.958 0.432]]


## 6. Execution Policies

HPXPy supports different execution policies for controlling parallelism.

In [19]:
# Check available execution policies
print("Available execution policies:")
print(f"  Sequential: {hpx.execution.seq}")
print(f"  Parallel:   {hpx.execution.par}")

Available execution policies:
  Sequential: <hpxpy._core.execution.sequenced_policy object at 0x108a44ff0>
  Parallel:   <hpxpy._core.execution.parallel_policy object at 0x108aac9f0>


## 7. Performance Example

Let's see parallel algorithms in action with a larger dataset.

In [20]:
import time

# Create a large array
n = 10_000_000
arr = hpx.random.uniform(0, 1000, size=n)

print(f"Array size: {n:,} elements")
print()

# Benchmark various operations
operations = [
    ("sum", lambda: hpx.sum(arr)),
    ("mean", lambda: hpx.mean(arr)),
    ("min/max", lambda: (hpx.min(arr), hpx.max(arr))),
    ("sqrt", lambda: hpx.sqrt(arr)),
    ("sin", lambda: hpx.sin(arr)),
]

for name, op in operations:
    start = time.time()
    result = op()
    elapsed = time.time() - start
    print(f"{name:10s}: {elapsed*1000:6.2f} ms")

Array size: 10,000,000 elements



sum       :   2.42 ms
mean      :   1.45 ms
min/max   :  12.68 ms
sqrt      :  14.19 ms


sin       :  30.38 ms


In [21]:
# Clean up
hpx.finalize()
print("Runtime finalized")

Runtime finalized


## Summary

In this tutorial, you learned:

1. **Math Functions**: `sqrt`, `exp`, `log`, `sin`, `cos`, `tan`, `sinh`, `cosh`, `tanh`, `floor`, `ceil`, `trunc`
2. **Element-wise Operations**: `maximum`, `minimum`, `clip`, `power`, `where`
3. **Sorting**: `sort`, `argsort`, `count`
4. **Scan Operations**: `cumsum`, `cumprod`
5. **Random Generation**: `rand`, `randn`, `uniform`, `randint`, `seed`
6. **Execution Policies**: `seq`, `par`

All these operations are parallelized and will automatically utilize multiple CPU cores.

Next tutorial: **Distributed Computing** - Learn about collective operations and distributed arrays.